name: Rust

on:
  push:
    branches: [ "main", "add-publishing" ]
    tags:
      - '**'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: cargo install cargo-get
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  debbuild:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
      - uses: actions/checkout@v4
      - name: Set up deb
        run: cargo install cargo-deb
      - name: Build deb
        run: cargo deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: target/debian/*.deb
          fail_on_unmatched_files: true
#      - name: Upload deb
#        uses: actions/upload-artifact@v2
#        with:
#          name: dechat-rs.deb
#          path: target/debian/*.deb

  archbuild:
    needs: [ build ]
    runs-on: ubuntu-latest
    container: ghcr.io/night-crawler/rust-arch:main
    name: Amd64Arch
    steps:
      - uses: actions/checkout@v4
      - name: Build pkg
        run: |
          chown -hR user: {./,/usr/local/cargo,/root} && sudo -Eu user cargo arch
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.pkg.tar.zst
          fail_on_unmatched_files: true
#      - name: Upload pkg
#        uses: actions/upload-artifact@v2
#        with:
#          name: dechat-rs.pkg.tar.zst
#          path: ./*.pkg.tar.zst
