name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  debbuild:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
      - uses: actions/checkout@v2
      - name: build .deb file
        uses: sassman/rust-deb-builder@v1
        with:
          target: x86_64-unknown-linux-gnu
      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: amd64deb
          path: ./target/x86_64-unknown-linux-gnu/debian/*.deb
