name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  debbuild:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
      - uses: actions/checkout@v4
      - name: Set up deb
        run: cargo install cargo-deb
      - name: Build deb
        run: cargo deb
      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: dechat-rs.deb
          path: target/debian/*.deb

  archbuild:
    needs: [ build ]
    runs-on: ubuntu-latest
    container: ghcr.io/night-crawler/rust-arch:main
    name: Amd64Arch
    steps:
      - run: whoami
      - uses: actions/checkout@v4
      - name: Build pkg
        run: cargo arch
      - name: Upload pkg
        uses: actions/upload-artifact@v2
        with:
          name: dechat-rs.pkg.tar.zst
          path: ./*.pkg.tar.zst
